/**
 * 臺南市立鹽水國中 114學年度家庭教育成果評鑑 資料庫
 */
const familyEduData = [
  {
    id: "theme-1",
    code: "主題 1",
    title: "家庭教育輔導團到校宣講活動",
    category: "lecture",
    categoryName: "宣講與教師研習",
    grade: "all",
    gradeName: "全校親師生",
    indicator: "3-1",
    indicatorName: "指標 3-1 輔導團宣講與推廣",
    description: "邀請臺南市家庭教育輔導團專業講師蒞校辦理全校宣講活動，協助師生增進家庭教育理念、促進家人溝通與自我成長。",
    highlights: ["輔導團專業講師授課", "全校師生踴躍參與", "強化家人關係與溝通技巧"],
    images: ["images/image001.jpg", "images/image002.jpg"],
    imageCaptions: ["輔導團講師到校宣講現況", "師生專心聆聽與互動討論"]
  },
  {
    id: "theme-2-1",
    code: "主題 2-1",
    title: "國一倫理教育：祖孫週微電影欣賞（爺爺 2.0）",
    category: "ethics",
    categoryName: "倫理教育與祖孫週",
    grade: "g7",
    gradeName: "國一年級",
    indicator: "2-1",
    indicatorName: "指標 2-1 倫理教育課程融入",
    description: "針對國一年級學生辦理祖孫週倫理教育活動，播放優質微電影《爺爺 2.0》，引導學生體驗祖孫互動之溫馨與科技對跨代溝通的影嚮。",
    highlights: ["影音媒體融入倫理教學", "引導國一學生珍惜祖孫情誼", "代間關懷與科技溝通議題"],
    images: ["images/image003.jpg", "images/image004.jpg"],
    imageCaptions: ["班級欣賞《爺爺 2.0》微電影", "學生專注觀賞與思考引導問題"]
  },
  {
    id: "theme-2-2",
    code: "主題 2-2",
    title: "國二倫理教育：祖孫週微電影欣賞（機器人與孤獨的婆婆）",
    category: "ethics",
    categoryName: "倫理教育與祖孫週",
    grade: "g8",
    gradeName: "國二年級",
    indicator: "2-1",
    indicatorName: "指標 2-1 倫理教育課程融入",
    description: "國二年級結合祖孫週主題，透過微電影《機器人與孤獨的婆婆》探討高齡化社會長者陪伴需求與家庭倫理，引發學生對家中長輩之深層關懷。",
    highlights: ["關懷獨居長者與陪伴議題", "國二班級深層倫理討論", "提升長輩心理陪伴意識"],
    images: ["images/image005.jpg", "images/image006.jpg"],
    imageCaptions: ["國二班級微電影教學進行中", "學生觀看影片並進行省思紀錄"]
  },
  {
    id: "theme-2-3",
    code: "主題 2-3",
    title: "國三倫理教育：祖孫週探討活動",
    category: "ethics",
    categoryName: "倫理教育與祖孫週",
    grade: "g9",
    gradeName: "國三年級",
    indicator: "2-1",
    indicatorName: "指標 2-1 倫理教育課程融入",
    description: "針對國三年級學生規劃祖孫週主題探討，引導即將畢業升學之國三學生發揚尊老敬老之傳統美德，感恩祖父母長期默默的付出與關愛。",
    highlights: ["國三尊老敬老倫理深化", "感恩長輩陪伴與教導", "促進跨世代家庭和諧"],
    images: ["images/image007.jpg", "images/image008.jpg"],
    imageCaptions: ["國三班級主題教學與欣賞現場", "祖孫週活動省思與討論"]
  },
  {
    id: "theme-3-1",
    code: "主題 3-1",
    title: "母親節活動：教師指導學生製作卡片",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "all",
    gradeName: "全校學生",
    indicator: "3-2",
    indicatorName: "指標 3-2 節慶感恩主題活動",
    description: "於母親節前夕，由美術與輔導教師聯合指導學生發揮創意，手作母親節感恩賀卡，表達對母親及家庭照顧者無限的感謝與敬意。",
    highlights: ["跨領域手作卡片教學", "學生用心書寫感謝心聲", "培養尊愛家庭照顧者態度"],
    images: ["images/image009.jpg", "images/image010.jpg"],
    imageCaptions: ["老師悉心指導學生製作卡片", "學生專注彩繪與書寫母親節卡片"]
  },
  {
    id: "theme-3-2",
    code: "主題 3-2",
    title: "母親節活動：櫥窗展示成果",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "all",
    gradeName: "全校學生",
    indicator: "3-2",
    indicatorName: "指標 3-2 節慶感恩主題活動",
    description: "將學生製作之優秀母親節卡片展示於校園輔導室主題櫥窗，打造充滿愛與溫馨的校園環境，營造感恩愛家的良好氛圍。",
    highlights: ["校園輔導櫥窗視覺策展", "展現學生豐富創作力", "營造全校愛家溫馨校園文化"],
    images: ["images/image011.jpg", "images/image012.jpg"],
    imageCaptions: ["母親節精美卡片立體櫥窗展示", "輔導室走廊櫥窗展示全景"]
  },
  {
    id: "theme-4-1",
    code: "主題 4-1",
    title: "國一祖父母節感恩卡片書寫活動",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "g7",
    gradeName: "國一年級",
    indicator: "3-2",
    indicatorName: "指標 3-2 節慶感恩主題活動",
    description: "響應教育部「祖父母節」，引導國一學生親手撰寫對祖父母（阿公、阿嬤、外公、外婆）的感恩卡片，傳遞濃濃的孫兒愛意與敬意。",
    highlights: ["真情實感祖孫情誼卡片", "學生手繪圖畫與感言", "傳遞跨世代倫理價值"],
    images: ["images/image013.jpg", "images/image014.jpg"],
    imageCaptions: ["學生給最親愛的阿嬤感恩卡卡片", "學生給最親愛的外婆真心話手繪卡"]
  },
  {
    id: "theme-4-2",
    code: "主題 4-2",
    title: "國二祖父母節感恩學習單（祖孫面對面）",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "g8",
    gradeName: "國二年級",
    indicator: "2-2",
    indicatorName: "指標 2-2 學習單實作與評量",
    description: "設計《祖孫面對面》學習單，讓國二學生訪談阿公阿嬤的珍貴寶貝與人生故事，調查對祖父母的瞭解程度，增進跨世代間的互動交流。",
    highlights: ["訪談阿公阿嬤的珍貴寶貝", "調查祖孫瞭解程度與心聲", "培養同理心與家族凝聚力"],
    images: ["images/image015.jpg", "images/image016.jpg"],
    imageCaptions: ["國二學生《阿公阿嬤的珍貴寶貝》學習單成果", "學生訪談紀錄與心靈省思心得"]
  },
  {
    id: "theme-4-3",
    code: "主題 4-3",
    title: "國三祖父母節感恩學習單",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "g9",
    gradeName: "國三年級",
    indicator: "2-2",
    indicatorName: "指標 2-2 學習單實作與評量",
    description: "國三年級配合祖父母節推動深入學習單，鼓勵高年級學生回顧成長過程中祖父母的呵護與教誨，強化家庭成員間的情感連結。",
    highlights: ["高年級學生情感深化", "反思家庭陪伴價值", "落實祖孫共融理念"],
    images: ["images/image017.jpg", "images/image018.jpg"],
    imageCaptions: ["國三祖父母節學習單佳作", "學生學習單實體展示與教師核章"]
  },
  {
    id: "theme-5",
    code: "主題 5",
    title: "學生書寫愛家傳真情卡片活動",
    category: "festival",
    categoryName: "節慶與感恩活動",
    grade: "all",
    gradeName: "全校學生",
    indicator: "3-2",
    indicatorName: "指標 3-2 節慶感恩主題活動",
    description: "辦理「愛家傳真情」全校性明信片與卡片書寫活動，鼓勵學生將平時害羞表達的愛與感謝化為文字，郵寄或親手遞交給家中親人。",
    highlights: ["全校性愛家行動實踐", "鼓勵主動表達情感", "促進家庭成員雙向互動"],
    images: ["images/image019.jpg", "images/image020.jpg"],
    imageCaptions: ["學生愛家傳真情卡片作品一", "學生愛家傳真情卡片作品二"]
  },
  {
    id: "theme-6-1",
    code: "主題 6-1",
    title: "國一 家庭教育影片融入學習單（鞋子不見了）",
    category: "video",
    categoryName: "影片融入教學",
    grade: "g7",
    gradeName: "國一年級",
    indicator: "2-3",
    indicatorName: "指標 2-3 多媒體融入家庭教育",
    description: "引導國一學生觀賞網路素養與同理心主題影片《鞋子不見了》，配合家庭教育學習單檢視個人上網習慣，防範沉迷網路並維護家庭關係和諧。",
    highlights: ["網路沉迷與自我控制議題", "家庭生活與網路使用平衡", "自我檢核表與行動省思"],
    images: ["images/image021.jpg", "images/image022.jpg"],
    imageCaptions: ["國一學習單《鞋子不見了》學生檢核實況一", "國一學習單《鞋子不見了》學生檢核實況二"]
  },
  {
    id: "theme-6-2-1",
    code: "主題 6-2",
    title: "國二家庭教育影片融入學習單 1（珍惜身邊的他）",
    category: "video",
    categoryName: "影片融入教學",
    grade: "g8",
    gradeName: "國二年級",
    indicator: "2-3",
    indicatorName: "指標 2-3 多媒體融入家庭教育",
    description: "運用生命教育與家庭情感議題影片《珍惜身邊的他》，引導國二學生珍惜與家人相處的時光，學習包容與體諒親人的付出。",
    highlights: ["珍惜家人相處時光", "學習感恩與體諒親人", "深化學生情感教育"],
    images: ["images/image023.jpg", "images/image024.jpg"],
    imageCaptions: ["國二《珍惜身邊的他》學習單展現一", "國二《珍惜身邊的他》學習單展現二"]
  },
  {
    id: "theme-6-2-2",
    code: "主題 6-2",
    title: "國二家庭教育影片融入學習單 2（愛使我們更靠近）",
    category: "video",
    categoryName: "影片融入教學",
    grade: "g8",
    gradeName: "國二年級",
    indicator: "2-3",
    indicatorName: "指標 2-3 多媒體融入家庭教育",
    description: "播放情感教育影片《愛使我們更靠近》，探討青少年同儕交往、異性相處與家庭父母溝通議題，引導學生學習主動與父母雙向溝通。",
    highlights: ["青少年異性交往與家庭溝通", "化解父母焦慮與衝突技巧", "培養健康人際與家庭價值觀"],
    images: ["images/image025.jpg", "images/image026.jpg"],
    imageCaptions: ["學生認真填寫《愛使我們更靠近》問答", "輔導室評語與肯定紀錄"]
  },
  {
    id: "theme-6-3",
    code: "主題 6-3",
    title: "國三家庭教育影片融入學習單（阿嬤的衛生紙）",
    category: "video",
    categoryName: "影片融入教學",
    grade: "g9",
    gradeName: "國三年級",
    indicator: "2-3",
    indicatorName: "指標 2-3 多媒體融入家庭教育",
    description: "國三年級結合影片《阿嬤的衛生紙》，探討高齡家庭生活細節、勤儉持家精神與長輩的生活智慧，增進國三學生對祖父母的尊重與理解。",
    highlights: ["體會長輩勤儉與愛意", "深耕國三倫理素養", "發揚傳承家庭美德"],
    images: ["images/image027.jpg", "images/image028.jpg"],
    imageCaptions: ["國三《阿嬤的衛生紙》學習單精選一", "國三《阿嬤的衛生紙》學習單精選二"]
  },
  {
    id: "theme-7-1",
    code: "主題 7-1",
    title: "國一家庭教育議題融入學習單（自編教材：甜蜜的家庭）",
    category: "curriculum",
    categoryName: "議題融入自編教材",
    grade: "g7",
    gradeName: "國一年級",
    indicator: "2-4",
    indicatorName: "指標 2-4 校本自編教材研發",
    description: "輔導組自編校本教材《甜蜜的家庭》，引導國一學生翻閱家庭舊相片，紀錄溫馨的家庭記憶與故事，表達對家人的期望與溫暖期待。",
    highlights: ["校本原創自編學習單", "結合家庭舊相片回憶錄", "培養愛家感懷情操"],
    images: ["images/image029.jpg", "images/image030.jpg"],
    imageCaptions: ["學生貼上家庭合照並撰寫溫馨故事", "《甜蜜的家庭》自編學習單優良作品展示"]
  },
  {
    id: "theme-7-2",
    code: "主題 7-2",
    title: "國二家庭教育議題融入學習單（自編教材：家庭金主張）",
    category: "curriculum",
    categoryName: "議題融入自編教材",
    grade: "g8",
    gradeName: "國二年級",
    indicator: "2-4",
    indicatorName: "指標 2-4 校本自編教材研發",
    description: "自編教材《家庭會議與家庭金主張》，指導國二學生練習模擬記錄家庭會議，透過民主討論與投票方式達成家庭旅遊或決策共識。",
    highlights: ["家庭會議流程與實務練習", "體驗家庭民主與溝通決策", "尊重每個成員的意見"],
    images: ["images/image031.jpg", "images/image032.jpg"],
    imageCaptions: ["國二學生模擬家庭會議紀錄作品一", "國二學生模擬家庭會議紀錄作品二"]
  },
  {
    id: "theme-7-3",
    code: "主題 7-3",
    title: "國三家庭教育議題融入學習單（自編教材：餐桌上愛的時光）",
    category: "curriculum",
    categoryName: "議題融入自編教材",
    grade: "g9",
    gradeName: "國三年級",
    indicator: "2-4",
    indicatorName: "指標 2-4 校本自編教材研發",
    description: "自編教材《餐桌上愛的時光》，引導國三學生分享家中最愛的一道菜與烹調者，記錄全家人圍爐共餐的歡樂對話，並學習幫忙準備餐具與家務。",
    highlights: ["分享家常菜與烹飪心意", "紀錄共餐溫馨對話", "鼓勵學生主動分擔家務"],
    images: ["images/image033.jpg", "images/image034.jpg"],
    imageCaptions: ["學生描繪最喜歡的一道菜與家族共餐時光", "學習單《餐桌上愛的時光》優秀作品評語"]
  },
  {
    id: "theme-8-1",
    code: "主題 8-1",
    title: "家庭教育議題融入各領域（國文領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "國文領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "將家庭教育議題融入國文科教學，選讀講述親情、孝道與家長教養相關文章，引導學生賞析文學名篇並感悟親情細膩之處。",
    highlights: ["文學經典閱讀與親情賞析", "增進語文表達與情感共鳴", "國文領域跨科整合教學"],
    images: ["images/image035.jpg", "images/image036.jpg"],
    imageCaptions: ["國文領域融入家庭教育教學教案", "國文課學習單實作紀錄"]
  },
  {
    id: "theme-8-2",
    code: "主題 8-2",
    title: "家庭教育議題融入各領域（英語領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "英語領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "英語領域結合 Family Tree（家族樹）、Family Members（家庭成員）與 Mother's Day Vocabulary 單元，讓學生以雙語介紹自己的家庭。",
    highlights: ["雙語介紹家庭與成員", "將生活經驗融入英語口語與寫作", "國際視野與家本位學習"],
    images: ["images/image037.jpg", "images/image038.jpg"],
    imageCaptions: ["英語領域家庭主題單字與句型教學", "學生英語 Family Card 作品展示"]
  },
  {
    id: "theme-8-3",
    code: "主題 8-3",
    title: "家庭教育議題融入各領域（數學領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "數學領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "數學科結合家庭收支預算、統計圖表與理財概念，引導學生計算家庭日常開銷與水電支出，體會父母維持家計的辛勞與理財重要性。",
    highlights: ["家庭理財與開銷統計計算", "培養學生珍惜資源觀念", "數學素養與家庭經濟結合"],
    images: ["images/image039.jpg", "images/image040.jpg"],
    imageCaptions: ["數學課家庭記帳與預算計算學習單", "學生分析家庭開銷圖表成果"]
  },
  {
    id: "theme-8-4",
    code: "主題 8-4",
    title: "家庭教育議題融入各領域（自然領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "自然領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "自然科學領域結合遺傳學、家族基因特徵與健康飲食營養，引導學生觀察家族遺傳特質與維護家庭成員健康飲食生活。",
    highlights: ["遺傳現象與基因觀察", "家庭健康營養與生活科學", "自然科學與家長健康連結"],
    images: ["images/image041.jpg", "images/image042.jpg"],
    imageCaptions: ["自然領域遺傳特徵調查學習單", "家庭營養健康飲食教案展示"]
  },
  {
    id: "theme-8-5",
    code: "主題 8-5",
    title: "家庭教育議題融入各領域（科技領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "科技領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "科技領域引導學生製作家庭生活智慧裝置或數位電子卡片，促進學生運用科技能力為家庭的生活品質與安全加分。",
    highlights: ["資訊科技創客手作", "設計家庭生活實用作品", "提昇科技倫理與愛家實踐"],
    images: ["images/image043.jpg", "images/image044.jpg"],
    imageCaptions: ["科技領域手作作品與家庭設計", "學生數位卡片設計展示"]
  },
  {
    id: "theme-8-6",
    code: "主題 8-6",
    title: "家庭教育議題融入各領域（社會領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "社會領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "社會領域公民與歷史課探討現代多元家庭型態、家事勞動分工與家庭相關法律權益（如 CEDAW 性別平等與家庭教育法規）。",
    highlights: ["探討多元家庭型態與平權", "家事分工與法律公民素養", "現代社會家庭變遷防護"],
    images: ["images/image045.jpg", "images/image046.jpg"],
    imageCaptions: ["社會領域 CEDAW 與家庭法規講義", "多元家庭議題學生討論學習單"]
  },
  {
    id: "theme-8-7",
    code: "主題 8-7",
    title: "家庭教育議題融入各領域（健體領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "健體領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "健康與體育領域推動親子運動、健康家庭習慣與情緒壓力調節，鼓勵學生帶動家中成員共同開展健康體能生活。",
    highlights: ["推廣親子體育運動", "情緒管理與壓力釋放", "營造健康活力家庭生活"],
    images: ["images/image047.jpg", "images/image001.jpg"],
    imageCaptions: ["健體領域健康家庭教學紀錄", "學生帶動家人運動紀錄表"]
  },
  {
    id: "theme-8-8",
    code: "主題 8-8",
    title: "家庭教育議題融入各領域（藝文領域）",
    category: "domain",
    categoryName: "各領域議題融入",
    grade: "all",
    gradeName: "藝文領域教學",
    indicator: "2-5",
    indicatorName: "指標 2-5 領域課程跨科融入",
    description: "藝文領域指導學生畫出家庭最溫馨的瞬間、創作繪本或唱詠家庭溫暖歌曲，讓美感與藝術深植於家庭情感關懷之中。",
    highlights: ["家庭主題繪畫與繪本創作", "美感教育融入情感表達", "呈現豐富視覺藝術成果"],
    images: ["images/image043.jpg", "images/image044.jpg"],
    imageCaptions: ["藝文領域繪畫成果作品集", "學生創作現場展現美感才華"]
  },
  {
    id: "theme-9-1",
    code: "主題 9-1",
    title: "性別平等教育活動（教師研習）",
    category: "lecture",
    categoryName: "宣講與教師研習",
    grade: "teachers",
    gradeName: "全校教師",
    indicator: "1-2",
    indicatorName: "指標 1-2 教師專業知能研習",
    description: "辦理全校教師性別平等教育與家庭教育專業知能研習，增進教師在課堂引導學生性別平權、防範數位性別暴力與情感溝通之專業知能。",
    highlights: ["增進教師性平與家庭知能", "探討現代家庭與性別議題", "落實校園與家庭雙重防護"],
    images: ["images/image035.jpg", "images/image036.jpg"],
    imageCaptions: ["全校教師性別平等教育研習現場一", "全校教師性別平等教育研習現場二"]
  },
  {
    id: "theme-9-2",
    code: "主題 9-2",
    title: "性別平等教育活動（教師入班宣導）",
    category: "lecture",
    categoryName: "宣講與教師研習",
    grade: "all",
    gradeName: "各班級學生",
    indicator: "3-3",
    indicatorName: "指標 3-3 性平與情感教育宣導",
    description: "輔導教師入班進行性別平等與情感教育宣導，引導學生建立尊重包容的性別態度、釐清身體自主權與人際交往分寸。",
    highlights: ["專業輔導教師入班精準宣導", "強化學生身體自主與尊重", "建立友善包容的同儕與家庭觀"],
    images: ["images/image037.jpg", "images/image038.jpg"],
    imageCaptions: ["輔導老師入班進行性平宣導畫面一", "輔導老師入班進行性平宣導畫面二"]
  },
  {
    id: "theme-10",
    code: "主題 10",
    title: "小團體輔導活動",
    category: "parenting",
    categoryName: "親職教育與親師座談",
    grade: "all",
    gradeName: "特定輔導學生",
    indicator: "4-1",
    indicatorName: "指標 4-1 輔導機制與小團體",
    description: "為需要人際互動與家庭適應支持之學生，開設主題式小團體輔導活動，透過牌卡、體驗互動增進學生自我概念與家庭適應能力。",
    highlights: ["小班制體驗式團體輔導", "提升學生心理抗壓與自信", "協助家庭適應困境學生"],
    images: ["images/image025.jpg", "images/image026.jpg"],
    imageCaptions: ["小團體輔導團體動力活動現場", "學生參與牌卡探索與分享紀錄"]
  },
  {
    id: "theme-11",
    code: "主題 11",
    title: "親職教育講座與活動",
    category: "parenting",
    categoryName: "親職教育與親師座談",
    grade: "parents",
    gradeName: "全校家長",
    indicator: "3-4",
    indicatorName: "指標 3-4 親職教育推廣講座",
    description: "邀請專家學者蒞校辦理親職教育大師講座，吸引眾多家長蒞臨參與，講授青春期子女溝通技巧、情緒管理與科技世代教養策略。",
    highlights: ["專家講師剖析青春期教養", "家長參與熱烈互動永躍", "有效提升親職溝通能力"],
    images: ["images/image039.jpg", "images/image040.jpg"],
    imageCaptions: ["禮堂親職教育講座全景", "家長專心聆聽講師精采演講內容"]
  },
  {
    id: "theme-12",
    code: "主題 12",
    title: "親師座談會活動",
    category: "parenting",
    categoryName: "親職教育與親師座談",
    grade: "parents",
    gradeName: "全校家長與導師",
    indicator: "1-4",
    indicatorName: "指標 1-4 親師合作與家長溝通",
    description: "每學期定期舉辦親師座談會，導師向家長說明班級經營理念、家庭教育推動方向，並建立緊密的親師合作橋樑，攜手陪伴學生成長。",
    highlights: ["建立良好親師溝通管道", "宣導學校家庭教育核心精神", "導師與家長深度座談"],
    images: ["images/image041.jpg", "images/image042.jpg"],
    imageCaptions: ["班級親師座談會導師說明現況一", "親師面對面交流與雙向溝通現況二"]
  },
  {
    id: "theme-13-1",
    code: "主題 13-1",
    title: "學生得獎作品：臺南市110年家庭教育小書繪本特優（鄭天立）",
    category: "honor",
    categoryName: "學生得獎與榮譽牆",
    grade: "all",
    gradeName: "學生：鄭天立",
    indicator: "4-2",
    indicatorName: "指標 4-2 學生家庭教育競賽榮譽",
    description: "參加「臺南市 110 年學校家庭教育學生主題創作徵選」，本校學生鄭天立發揮卓越創意與藝術才華，榮獲「國中組小書繪本－特優」最高榮譽！",
    highlights: ["全市家庭教育小書繪本最高特優獎", "細緻描繪家族溫馨共餐與日常生活", "展現鹽水國中學生極佳藝文才華"],
    images: ["images/image043.jpg", "images/image044.jpg"],
    imageCaptions: ["鄭天立特優繪本內頁：大家一起歡聚吃晚餐", "特優繪本手繪作品細節展示"]
  },
  {
    id: "theme-13-2-1",
    code: "主題 13-2",
    title: "學生得獎獎狀：臺南市110年度校園 CEDAW 日繪畫甲等（何青薌）",
    category: "honor",
    categoryName: "學生得獎與榮譽牆",
    grade: "all",
    gradeName: "學生：何青薌",
    indicator: "4-2",
    indicatorName: "指標 4-2 學生家庭教育競賽榮譽",
    description: "本校學生何青薌參加「臺南市 110 年度校園 CEDAW 日繪畫甄選活動」，作品表現優異，榮獲普通班國中組「甲等」殊榮！",
    highlights: ["臺南市政府教育局頒發市長黃偉哲獎狀", "落實 CEDAW 性別平等與家事分工理念", "肯定學校藝術與性平教育成果"],
    images: ["images/image045.jpg"],
    imageCaptions: ["何青薌同學獲頒臺南市政府甲等獎狀證書"]
  },
  {
    id: "theme-13-2-2",
    code: "主題 13-2",
    title: "學生得獎獎狀：臺南市110年度校園 CEDAW 日繪畫佳作（溫青烜、吳婕菱）",
    category: "honor",
    categoryName: "學生得獎與榮譽牆",
    grade: "all",
    gradeName: "學生：溫青烜、吳婕菱",
    indicator: "4-2",
    indicatorName: "指標 4-2 學生家庭教育競賽榮譽",
    description: "本校學生溫青烜、吳婕菱參與「臺南市 110 年度校園 CEDAW 日繪畫甄選活動」，以獨特視角表現家庭性平意識，雙雙榮獲普通班國中組「佳作」！",
    highlights: ["雙名學生榮獲全市佳作肯定", "展現校園對性別平等教育的落實", "激勵全校同學積極投入創意繪畫"],
    images: ["images/image046.jpg"],
    imageCaptions: ["溫青烜、吳婕菱同學榮獲佳作獎狀證書"]
  },
  {
    id: "theme-13-3",
    code: "主題 13-3",
    title: "學生得獎作品：臺南市111年度校園 CEDAW 日繪畫佳作（李宜軒）",
    category: "honor",
    categoryName: "學生得獎與榮譽牆",
    grade: "all",
    gradeName: "學生：李宜軒",
    indicator: "4-2",
    indicatorName: "指標 4-2 學生家庭教育競賽榮譽",
    description: "本校學生李宜軒參加「臺南市 111 年度校園 CEDAW 日繪畫甄選活動」，憑藉豐富生動的色彩與豐富內涵，榮獲普通班國中組「佳作」！",
    highlights: ["精彩繪畫作品呈現警察、軍人等多元性別職業", "傳達打破性別刻板印象重要理念", "表現出色獲專家評審青睞"],
    images: ["images/image047.jpg"],
    imageCaptions: ["李宜軒學生精彩得獎繪畫作品《CEDAW 尊重與平等》"]
  },
  {
    id: "theme-14",
    code: "主題 14",
    title: "社區生活營：個別諮商親職教育講座",
    category: "community",
    categoryName: "社區生活營與心理健康",
    grade: "parents",
    gradeName: "社區家長與學生",
    indicator: "4-3",
    indicatorName: "指標 4-3 社區資源整合與陪伴",
    description: "結合社區生活營資源，邀請專業心理師進駐學校辦理「個別諮商與親職教育講座」，提供家長一對一精準親職諮詢服務。",
    highlights: ["專業心理諮商師個別指導", "深入解決特定家庭親職困境", "成功結合社區醫療與輔導資源"],
    images: ["images/image023.jpg", "images/image024.jpg"],
    imageCaptions: ["個別諮商與親職教育會談現場一", "個別諮商與親職教育會談現場二"]
  },
  {
    id: "theme-15",
    code: "主題 15",
    title: "社區生活營：療程式小團體活動",
    category: "community",
    categoryName: "社區生活營與心理健康",
    grade: "all",
    gradeName: "特定需求學生",
    indicator: "4-3",
    indicatorName: "指標 4-3 社區資源整合與陪伴",
    description: "引進社區生活營專業師資，辦理「療程式小團體」輔導，透過牌卡探索、表達性藝術與團隊互動，陪伴學生舒緩情緒壓力。",
    highlights: ["藝術與牌卡表達性療程", "建立安全支持性同儕團體", "提昇高關懷學生心理韌性"],
    images: ["images/image025.jpg", "images/image026.jpg"],
    imageCaptions: ["療程式小團體成員環坐探索遊戲", "團體成員進行卡片與藝術創作分享"]
  },
  {
    id: "theme-16",
    code: "主題 16",
    title: "心能力 2.0──幸運憂轉宣導活動",
    category: "community",
    categoryName: "社區生活營與心理健康",
    grade: "all",
    gradeName: "全校學生",
    indicator: "3-1",
    indicatorName: "指標 3-1 心理健康與家庭輔導宣導",
    description: "推動《心能力 2.0──幸運憂轉》情緒管理與憂鬱防範宣導活動，教導學生認識情緒、尋求家庭與學校支援，促進心理健康與和諧人際關係。",
    highlights: ["情緒覺察與憂鬱防治", "強化校園與家庭防護網", "學生展現豐富學習心得"],
    images: ["images/image021.jpg", "images/image022.jpg"],
    imageCaptions: ["班級推動《心能力 2.0》宣導現場", "學生代表展示宣導心得與成果卡"]
  },
  {
    id: "theme-17",
    code: "主題 17",
    title: "當我更安心－網路使用與家庭和諧講座",
    category: "community",
    categoryName: "社區生活營與心理健康",
    grade: "all",
    gradeName: "全校學生",
    indicator: "3-1",
    indicatorName: "指標 3-1 專題講座與安全防護",
    description: "辦理「當我更安心－網路安全與健康使用講座」，引導學生正視網路交友安全、防止網路沉迷，並主動與家長建立良好的網路使用約定。",
    highlights: ["網路安全與詐騙防範宣導", "促進親子簽訂健康網路約定", "大型禮堂專題宣導活動"],
    images: ["images/image001.jpg", "images/image002.jpg"],
    imageCaptions: ["學生活動中心網路講座全景", "學生填寫網路使用問券與心得紀錄"]
  }
];

// 指標對照分類對照表
const evaluationCriteria = [
  {
    id: "indicator-1",
    title: "指標一：行政組織與推動計畫",
    items: [
      { code: "1-1", name: "家庭教育推行委員會與年度實施計畫", mappedThemes: ["theme-1"] },
      { code: "1-2", name: "教師專業知能研習與進修", mappedThemes: ["theme-9-1"] },
      { code: "1-4", name: "親師合作與家長雙向溝通", mappedThemes: ["theme-12"] }
    ]
  },
  {
    id: "indicator-2",
    title: "指標二：家庭教育課程與教學",
    items: [
      { code: "2-1", name: "倫理教育與代間關懷課程融入", mappedThemes: ["theme-2-1", "theme-2-2", "theme-2-3"] },
      { code: "2-2", name: "多元學習單設計與學生實作評量", mappedThemes: ["theme-4-2", "theme-4-3"] },
      { code: "2-3", name: "多媒體影音融入家庭教育教學", mappedThemes: ["theme-6-1", "theme-6-2-1", "theme-6-2-2", "theme-6-3"] },
      { code: "2-4", name: "校本原創自編教材與議題研發", mappedThemes: ["theme-7-1", "theme-7-2", "theme-7-3"] },
      { code: "2-5", name: "全領域課程跨科融入（國文、英語、數學、自然、科技、社會、健體、藝文）", mappedThemes: ["theme-8-1", "theme-8-2", "theme-8-3", "theme-8-4", "theme-8-5", "theme-8-6", "theme-8-7", "theme-8-8"] }
    ]
  },
  {
    id: "indicator-3",
    title: "指標三：宣講與主題推廣活動",
    items: [
      { code: "3-1", name: "輔導團宣講、心理健康與網路安全", mappedThemes: ["theme-1", "theme-16", "theme-17"] },
      { code: "3-2", name: "節慶感恩活動（母親節、祖父母節、愛家傳真情）", mappedThemes: ["theme-3-1", "theme-3-2", "theme-4-1", "theme-5"] },
      { code: "3-3", name: "性別平等與情感教育宣導", mappedThemes: ["theme-9-2"] },
      { code: "3-4", name: "親職教育講座與家長成長活動", mappedThemes: ["theme-11"] }
    ]
  },
  {
    id: "indicator-4",
    title: "指標四：輔導機制、競賽榮譽與社區資源整合",
    items: [
      { code: "4-1", name: "高關懷學生小團體輔導與心理支持", mappedThemes: ["theme-10"] },
      { code: "4-2", name: "學生家庭教育主題競賽與繪本得獎榮譽", mappedThemes: ["theme-13-1", "theme-13-2-1", "theme-13-2-2", "theme-13-3"] },
      { code: "4-3", name: "社區生活營與專業心理諮商資源整合", mappedThemes: ["theme-14", "theme-15"] }
    ]
  }
];
